package erp.javaguides.erpbackend.mapper;

import erp.javaguides.erpbackend.dto.StudentDto;
import erp.javaguides.erpbackend.dto.StudentWithFilesDto;
import erp.javaguides.erpbackend.entity.Student;



public class StudentMapper {

    public static StudentWithFilesDto mapToStudentWithFilesDto(Student student){
        return new StudentWithFilesDto(
                student.getRegisterNo(),
                student.getFirstName(),
                student.getLastName(),
                student.getDateOfBirth(),
                student.getGender(),
                student.getAadharNumber(),
                student.getNationality(),
                student.getReligion(),
                student.getCommunity(),
                student.getCaste(),
                student.getFathersName(),
                student.getFathersOccupation(),
                student.getFathersMobileNumber(),
                student.getMothersName(),
                student.getMothersOccupation(),
                student.getMothersMobileNumber(),
                student.getGuardiansName(),
                student.getGuardiansOccupation(),
                student.getGuardiansMobileNumber(),
                student.getParentsStatus(),
                student.getIncome(),
                student.getMaritalStatus(),
                student.getMobileNumber(),
                student.getEmailid(),
                student.getResidentialAddress(),
                student.getCommunicationAddress(),
                student.getHosteller(),
                student.getHostelType(),
                student.getBankName(),
                student.getIfscCode(),
                student.getBranchName(),
                student.getAccountNumber(),
                student.getSslc(),
                student.getHsc1Year(),
                student.getHsc2Year(),
                student.getDiploma(),
                student.getEmisNumber(),
                student.getFirstGraduate(),
                student.getSpecialCategory(),
                null,
                null,
                null,
                null,
                null,
                null,
               // null,
                null,
                null,
                null,
                null,
                null,
                student.getProgramme(),
                student.getDiscipline(),
                student.getAdmissionNumber(),
                student.getAcademicYear(),
                student.getSemester(),
                student.getAbcId(),
                student.getUmisId(),
                student.getDateOfAdmission(),
                student.getCourseJoinedDate(),
                student.getCourseType(),
                student.getRegulation(),
                student.getFastTrack(),
                student.getCgpa(),
                student.getStudentStatus()
        );
    }

    public static Student mapToStudentWithFilesDto(StudentWithFilesDto studentWithFilesDto){
        return new Student(
                studentWithFilesDto.getRegisterNo(),
                studentWithFilesDto.getFirstName(),
                studentWithFilesDto.getLastName(),
                studentWithFilesDto.getDateOfBirth(),
                studentWithFilesDto.getGender(),
                studentWithFilesDto.getAadharNumber(),
                studentWithFilesDto.getNationality(),
                studentWithFilesDto.getReligion(),
                studentWithFilesDto.getCommunity(),
                studentWithFilesDto.getCaste(),
                studentWithFilesDto.getFathersName(),
                studentWithFilesDto.getFathersOccupation(),
                studentWithFilesDto.getFathersMobileNumber(),
                studentWithFilesDto.getMothersName(),
                studentWithFilesDto.getMothersOccupation(),
                studentWithFilesDto.getMothersMobileNumber(),
                studentWithFilesDto.getGuardiansName(),
                studentWithFilesDto.getGuardiansOccupation(),
                studentWithFilesDto.getGuardiansMobileNumber(),
                studentWithFilesDto.getParentsStatus(),
                studentWithFilesDto.getIncome(),
                studentWithFilesDto.getMaritalStatus(),
                null,
                studentWithFilesDto.getMobileNumber(),
                studentWithFilesDto.getEmailid(),
                studentWithFilesDto.getResidentialAddress(),
                studentWithFilesDto.getCommunicationAddress(),
                studentWithFilesDto.getHosteller(),
                studentWithFilesDto.getHostelType(),
                studentWithFilesDto.getBankName(),
                studentWithFilesDto.getIfscCode(),
                studentWithFilesDto.getBranchName(),
                studentWithFilesDto.getAccountNumber(),
                null,
                studentWithFilesDto.getSslc(),
                studentWithFilesDto.getHsc1Year(),
                studentWithFilesDto.getHsc2Year(),
                studentWithFilesDto.getDiploma(),
                null,
                null,
                null,
                null,
                studentWithFilesDto.getEmisNumber(),
                studentWithFilesDto.getFirstGraduate(),
                studentWithFilesDto.getSpecialCategory(),
                studentWithFilesDto.getProgramme(),
                studentWithFilesDto.getDiscipline(),
                studentWithFilesDto.getAdmissionNumber(),
                studentWithFilesDto.getAcademicYear(),
                studentWithFilesDto.getSemester(),
                studentWithFilesDto.getAbcId(),
                studentWithFilesDto.getUmisId(),
                studentWithFilesDto.getDateOfAdmission(),
                studentWithFilesDto.getCourseJoinedDate(),
                studentWithFilesDto.getCourseType(),
                studentWithFilesDto.getRegulation(),
                studentWithFilesDto.getFastTrack(),
                studentWithFilesDto.getCgpa(),
                studentWithFilesDto.getStudentStatus()
        );
    }
}