package erp.javaguides.erpbackend.mapper;

import erp.javaguides.erpbackend.dto.requestDto.StudentDto;
import erp.javaguides.erpbackend.dto.responseDto.StudentResponseDto;
import erp.javaguides.erpbackend.entity.Student;
import erp.javaguides.erpbackend.utility.UtilityService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class StudentMapper {
    @Autowired
    private static UtilityService utilityService;

    public static StudentDto mapToStudentWithFilesDto(Student student){
        return new StudentDto(
                student.getRegisterNo(),
                student.getFirstName(),
                student.getLastName(),
                student.getDateOfBirth(),
                student.getGender(),
                student.getAadharNumber(),
                student.getBloodGroup(),
                student.getNationality(),
                student.getState(),
                student.getReligion(),
                student.getCommunity(),
                student.getCaste(),
                student.getFatherName(),
                student.getFatherOccupation(),
                student.getFatherMobileNumber(),
                student.getMotherName(),
                student.getMotherOccupation(),
                student.getMotherMobileNumber(),
                student.getGuardianName(),
                student.getGuardianOccupation(),
                student.getGuardianMobileNumber(),
                student.getParentStatus(),
                student.getIncome(),
                student.getMaritalStatus(),
                null,
                null,
                null,
                null,
                student.getMobileNumber(),
                student.getEmailId(),
                student.getResidentialAddress(),
                student.getCommunicationAddress(),
                student.getHosteller(),
                student.getHostelType(),
                student.getBankName(),
                student.getIfscCode(),
                student.getBankBranchName(),
                student.getBankAccountNumber(),
                null,
                null,
                student.getSslcPercent(),
                student.getHscFirstYearPercent(),
                student.getHscSecondYearPercent(),
                student.getDiplomaPercent(),
                student.getSslcFilePath(),
                student.getHscFirstYearFilePath(),
                student.getHscSecondYearFilePath(),
                student.getDiplomaFilePath(),
                null,
                null,
                null,
                null,
                student.getEmisNumber(),
                student.getFirstGraduate(),
                student.getSpecialCategory(),
                student.getAadharCardFilePath(),
                null,
                null,
                null,
                null,
                null,
                student.getProgramme(),
                student.getDiscipline(),
                student.getDepartment(),
                student.getClassSection(),
                student.getAdmissionNumber(),
                student.getBatch(),
                student.getSemester(),
                student.getAbcId(),
                student.getUmisId(),
                student.getDateOfAdmission(),
                student.getCourseJoinedDate(),
                student.getCourseType(),
                student.getRegulation(),
                student.getCgpa(),
                student.getIsGovtSchool(),
                student.getStudentStatus(),
                (student.getFaculty()==null)? null:student.getFaculty().getFacultyId()

        );
    }

    public static Student mapToStudentWithFilesDto(StudentDto studentDto){
        return new Student(
                studentDto.getRegisterNo(),
                studentDto.getFirstName(),
                studentDto.getLastName(),
                utilityService.yearMonthDayToDayMonthYear(studentDto.getDateOfBirth()),
                studentDto.getGender(),
                studentDto.getAadharNumber(),
                studentDto.getBloodGroup(),
                studentDto.getNationality(),
                studentDto.getState(),
                studentDto.getReligion(),
                studentDto.getCommunity(),
                studentDto.getCaste(),
                studentDto.getFathersName(),
                studentDto.getFathersOccupation(),
                studentDto.getFathersMobileNumber(),
                studentDto.getMothersName(),
                studentDto.getMothersOccupation(),
                studentDto.getMothersMobileNumber(),
                studentDto.getGuardiansName(),
                studentDto.getGuardiansOccupation(),
                studentDto.getGuardiansMobileNumber(),
                studentDto.getParentsStatus(),
                studentDto.getIncome(),
                studentDto.getMaritalStatus(),
                null,
                null,
                studentDto.getMobileNumber(),
                studentDto.getEmailid(),
                studentDto.getResidentialAddress(),
                studentDto.getCommunicationAddress(),
                studentDto.getHosteller(),
                studentDto.getHostelType(),
                studentDto.getBankName(),
                studentDto.getIfscCode(),
                studentDto.getBranchName(),
                studentDto.getAccountNumber(),
                null,
                studentDto.getSslc(),
                studentDto.getHsc1Year(),
                studentDto.getHsc2Year(),
                studentDto.getDiploma(),
                null,
                null,
                null,
                null,
                studentDto.getEmisNumber(),
                studentDto.getFirstGraduate(),
                studentDto.getSpecialCategory(),
                null,
                null,
                studentDto.getProgramme(),
                studentDto.getDiscipline(),
                studentDto.getDepartment(),
                studentDto.getClassSection(),
                studentDto.getAdmissionNumber(),
                studentDto.getBatch(),
                studentDto.getSemester(),
                studentDto.getAbcId(),
                studentDto.getUmisId(),
                UtilityService.yearMonthDayToDayMonthYear(studentDto.getDateOfAdmission()),
                UtilityService.yearMonthDayToDayMonthYear(studentDto.getCourseJoinedDate()),
                studentDto.getCourseType(),
                studentDto.getRegulation(),
                studentDto.getCgpa(),
                studentDto.getIsGovtSchool(),
                studentDto.getStudentStatus()

        );
    }

    public static StudentResponseDto mapToStudentResponseDto(Student student) {
        return new StudentResponseDto(
                student.getRegisterNo(),
                student.getFirstName(),
                student.getLastName(),
                student.getGender(),
                student.getEmailId(),
                student.getMobileNumber(),
                student.getDateOfBirth(),
                student.getProgramme(),
                student.getDiscipline(),
                student.getDepartment(),
                student.getClassSection(),
                student.getSemester(),
                student.getBatch(),
                student.getCgpa(),
                (student.getFaculty()==null)? null:student.getFaculty().getFacultyId()
        );
    }
}